apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kntz5pfie-nodejs 
  janus-idp.io/tekton: kntz5pfie-nodejs
  backstage.io/kubernetes-id: kntz5pfie-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kntz5pfie-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml