apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kntz5pfie-nodejs
  janus-idp.io/tekton: kntz5pfie-nodejs
  backstage.io/kubernetes-id: kntz5pfie-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kntz5pfie-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
